# Generated by Django 5.2.1 on 2025-06-07 05:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.material_id),
        ),
    ]
