# Generated by Django 5.2.1 on 2025-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursematerial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='external_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Link'), ('link', 'External Link')], max_length=10),
        ),
    ]
